ARG ALPINE_VERSION=3.12


FROM alpine:${ALPINE_VERSION}
WORKDIR /home/packager

ARG GIT_TAG
ARG GIT_REV 
ARG BUILD_TYPE=False
ARG MONGODB_SUPPORT=ON
ADD APKBUILD APKBUILD
ADD hwpc.post-install hwpc.post-install
RUN apk update && apk add alpine-sdk build-base sudo && \
    adduser -D packager  \
    && addgroup packager abuild \
    && echo "packager ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/packager 

USER packager
RUN abuild-keygen -a -i -n \
    && abuild -r 
