name: Build Docker Image and Retrieve Artifact

on:
    push:
        branches:
            - alpine

env:
    ALPINE_VERSION: 3.12
    Package_version: 0.3-r6

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: |
                  docker build . --file Dockerfile --tag hwpc-alpine:${{ env.ALPINE_VERSION }} --build-arg ALPINE_VERSION=${{ env.ALPINE_VERSION }}

            - name: Save Docker image as a tar file
              run: docker save hwpc-alpine:${{ env.ALPINE_VERSION }} > image.tar
            - name: Upload Docker image as a workflow artifact
              uses: actions/upload-artifact@v3
              with:
                  name: docker-image-alpine-${{ env.ALPINE_VERSION }}
                  path: image.tar

    retrieve-artifact:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: Download Docker image artifact
              uses: actions/download-artifact@v3
              with:
                  name: docker-image-alpine-${{ env.ALPINE_VERSION }}
            - name: Load Docker image from tar file
              run: docker load < image.tar
            - name: Run Docker image
              run: docker run --name runner hwpc-alpine:${{ env.ALPINE_VERSION }}
            - name: retrieve the data from the container
              run: docker cp runner:/home/packager/packages/home/x86_64/hwpc-${{env.Package_version}}.apk .
            - name: publish the apk file to github
              uses: actions/upload-artifact@v3
              with:
                  name: hwpc-${{env.Package_version}}.apk
                  path: hwpc-${{env.Package_version}}.apk
