name: Release workflow

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  check_version:
    name: Check sensor version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Check tag and sensor version
        id: step1
        run: |
          export VERSION=$(echo $GITHUB_REF | sed -e 's/refs\/tags\/v//g')
          test $VERSION == $(grep Version control | cut -d ' ' -f 2)
          echo "::set-output name=version::$VERSION"
  build:
    name: Build binary
    needs: check_version
    runs-on: ubuntu-latest
    container:
      image: powerapi/hwpc-sensor-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Create environement
        run: |
          mkdir build
          cd build
          GIT_TAG=$(git describe --tags --dirty 2>/dev/null || echo "unknown")
          GIT_REV=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
      - name: Create Makefiles
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_C_CLANG_TIDY="clang-tidy" -DWITH_MONGODB="${MONGODB_SUPPORT}" ..
      - name: Build sensor
        run: |
          cd build
          make -j $(getconf _NPROCESSORS_ONLN)
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: build/hwpc-sensor 
  build_deb:
    name: Build debian package
    needs: [check_version, build]
    runs-on: ubuntu-latest
    container:
      image: powerapi/hwpc-sensor-build:latest
    env:
      VERSION: ${{needs.check_version.outputs.version}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: binary
          path: ~/bin/
      - name: Create package source
        run: |
          mkdir -p hwpc-sensor-$VERSION/DEBIAN
          cp control hwpc-sensor-$VERSION/DEBIAN/
          mkdir -p hwpc-sensor-$VERSION/usr/bin/
          cp ~/bin/hwpc-sensor hwpc-sensor-$VERSION/usr/bin/hwpc-sensor
          chmod +x hwpc-sensor-$VERSION/usr/bin/hwpc-sensor
          dpkg-deb --build hwpc-sensor-$VERSION
      - uses: actions/upload-artifact@v2
        with:
          name: deb_package
          path: hwpc-sensor-${{needs.check_version.outputs.version}}.deb
  publish_release:
    name: Publish release on github
    runs-on: ubuntu-latest
    needs: [check_version, build_deb]
    env:
      VERSION: ${{needs.check_version.outputs.version}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: binary
          path: ~/assets/
      - uses: actions/download-artifact@v2
        with:
          name: deb_package
          path: ~/assets/
      - name: Create Changelog
        env:
          CHANGELOG_CONTENT: ${{ steps.changelog.outputs.clean_changelog }}
        run: |
          sudo apt install -y npm
          sudo npm install -g conventional-changelog-cli
          conventional-changelog -p angular -r 2 | grep -v "^# \[\]" | sed 's/^#//g' > ~/final-changelog.md
          cat ~/final-changelog.md
          cat ~/final-changelog.md >> CHANGELOG.md
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v$VERSION -d -t v$VERSION -F ~/final-changelog.md ~/assets/*

